### ISSUE TITLE
Not update component on ternary

### ISSUE THREAD

**Issue by peeweesilva** [nullstack/nullstack#137] opened 2021-12-29 18:34 UTC
The components not change on the render view when use on conditional ternary operator
example: 

```
variable = true
render () {
return (
  <section>{ variable ? <ComponentA /> : <ComponentB /> }</section>
}
```

if you change the variable to false the render will continue to show the ComponentA

**Comment by GuiDevloper** [comment] 2021-12-30 20:29
Hey @peeweesilva, did you mean to use `this.variable`?
And to reactively update it, would be:
```jsx
this.variable = !this.variable
```

**Comment by Mortaro** [comment] 2021-12-30 20:47
@peeweesilva @GuiDevloper i was there while the issue happened.

The test case was with "me" coming from context like:

```jsx
render ({ me }) {
  return (
    <section>{ me? <ComponentA /> : <ComponentB /> }</section>
    )
 }
```

**Comment by peeweesilva** [comment] 2022-01-01 14:24
@Mortaro @GuiDevloper sorry for the simple example
Here is one better and tested example of the  https://github.com/peeweesilva/nullstack-issue-137
The issue looks happening only when you use outer components

**Comment by Mortaro** [comment] 2022-01-01 20:07
@peeweesilva this example is awesome! I managed to reproduce the issue and will look into it this weekend. thanks!

@GuiDevloper tasukete! ಥ_ಥ

**Comment by Mortaro** [comment] 2022-01-01 21:02
[WIP]
After some test, seems like the problem is that instead of defining `render` ComponentD is defining `renderComponentD` and i didnt notice that before https://github.com/peeweesilva/nullstack-issue-137/blob/5a3266775a0c9f6ea96ccc09699948d9717658ac/src/components/ComponentD.njs#L4

However even after fixing that its not working as it should since its sharing instances with the same key. ill add the class name as a criteria to the key

**Comment by peeweesilva** [comment] 2022-01-01 21:11
what do you think to instead of use the class name, which can be the same, or do not have anything for fragments, always create an unique key for each component?

Does this will be overworking and/or overthinking?

Thanks

**Comment by Mortaro** [comment] 2022-01-01 21:53
Creating unique keys per component would break the persistent components (or make it heavier to compute), ideally we would have an `object_id` equivalent for the class itself (from ruby) but JavaScript does not and the overhead might be overkill compared to just warning the user if two components have same name and same depth that it would have weird behavior.

If anyone has a low cost solution for this we could still implement before merge

the issue is fixed on this PR https://github.com/nullstack/nullstack/pull/142/files but still missing tests

@peeweesilva or @GuiDevloper if one of you want to add tests it would be as simple as creating a ClassTernary.njs and a ClassTernary.test.js following the pattern from any other test

**Comment by Mortaro** [comment] 2022-01-07 02:32
This is fixed and currently merged into #next, but could use better test coverage (っ °Д °;)っ

**Comment by Mortaro** [comment] 2022-02-07 00:31
Tests added, closing this issue, thanks everyone!

**Closed by Mortaro** 2022-02-07 00:31 UTC
